//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /mnt/LinuxTools/LinuxRepos/Stark/Stark.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Stark.Parsing {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="StarkParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IStarkVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilationUnit([NotNull] StarkParser.CompilationUnitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.importDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportDeclaration([NotNull] StarkParser.ImportDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.moduleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclaration([NotNull] StarkParser.ModuleDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.attributeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeList([NotNull] StarkParser.AttributeListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] StarkParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.attributeArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeArgument([NotNull] StarkParser.AttributeArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.topLevelDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTopLevelDeclaration([NotNull] StarkParser.TopLevelDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.visibilityModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVisibilityModifier([NotNull] StarkParser.VisibilityModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclaration([NotNull] StarkParser.FunctionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.functionKind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionKind([NotNull] StarkParser.FunctionKindContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.functionModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionModifier([NotNull] StarkParser.FunctionModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnType([NotNull] StarkParser.ReturnTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] StarkParser.ParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] StarkParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.parameterContractPrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterContractPrefix([NotNull] StarkParser.ParameterContractPrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.parameterMemoryContractClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterMemoryContractClause([NotNull] StarkParser.ParameterMemoryContractClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.parameterMemoryContract"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterMemoryContract([NotNull] StarkParser.ParameterMemoryContractContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.disjointContract"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDisjointContract([NotNull] StarkParser.DisjointContractContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.overlapContract"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOverlapContract([NotNull] StarkParser.OverlapContractContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.sameContract"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSameContract([NotNull] StarkParser.SameContractContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.typeParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParameterList([NotNull] StarkParser.TypeParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParameter([NotNull] StarkParser.TypeParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.typeParameterConstraints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParameterConstraints([NotNull] StarkParser.TypeParameterConstraintsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionBody([NotNull] StarkParser.FunctionBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.asmSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsmSpecifier([NotNull] StarkParser.AsmSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.asmClauseList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsmClauseList([NotNull] StarkParser.AsmClauseListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.asmClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsmClause([NotNull] StarkParser.AsmClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.asmInputClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsmInputClause([NotNull] StarkParser.AsmInputClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.asmOutputClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsmOutputClause([NotNull] StarkParser.AsmOutputClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.asmClobberClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsmClobberClause([NotNull] StarkParser.AsmClobberClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.asmFunctionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsmFunctionBody([NotNull] StarkParser.AsmFunctionBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDeclaration([NotNull] StarkParser.StructDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.recordDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecordDeclaration([NotNull] StarkParser.RecordDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDeclaration([NotNull] StarkParser.EnumDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.traitDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTraitDeclaration([NotNull] StarkParser.TraitDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.doctrineDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoctrineDeclaration([NotNull] StarkParser.DoctrineDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.typeAliasDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeAliasDeclaration([NotNull] StarkParser.TypeAliasDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.primaryConstructorParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryConstructorParameters([NotNull] StarkParser.PrimaryConstructorParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.baseTraitList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseTraitList([NotNull] StarkParser.BaseTraitListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.structBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructBody([NotNull] StarkParser.StructBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.recordBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecordBody([NotNull] StarkParser.RecordBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumBody([NotNull] StarkParser.EnumBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.traitBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTraitBody([NotNull] StarkParser.TraitBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.doctrineBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoctrineBody([NotNull] StarkParser.DoctrineBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.structMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructMember([NotNull] StarkParser.StructMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.recordMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecordMember([NotNull] StarkParser.RecordMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.enumVariantDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumVariantDeclaration([NotNull] StarkParser.EnumVariantDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.enumVariantPayload"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumVariantPayload([NotNull] StarkParser.EnumVariantPayloadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.enumVariantFieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumVariantFieldDeclaration([NotNull] StarkParser.EnumVariantFieldDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.traitMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTraitMember([NotNull] StarkParser.TraitMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.doctrineMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoctrineMember([NotNull] StarkParser.DoctrineMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldDeclaration([NotNull] StarkParser.FieldDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodDeclaration([NotNull] StarkParser.MethodDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.traitMethodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTraitMethodDeclaration([NotNull] StarkParser.TraitMethodDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.doctrineMethodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoctrineMethodDeclaration([NotNull] StarkParser.DoctrineMethodDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.doctrineFunctionKind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoctrineFunctionKind([NotNull] StarkParser.DoctrineFunctionKindContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.constructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorDeclaration([NotNull] StarkParser.ConstructorDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.destructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDestructorDeclaration([NotNull] StarkParser.DestructorDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.globalConstantDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalConstantDeclaration([NotNull] StarkParser.GlobalConstantDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.globalVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalVariableDeclaration([NotNull] StarkParser.GlobalVariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.constantDeclarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantDeclarators([NotNull] StarkParser.ConstantDeclaratorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.constantDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantDeclarator([NotNull] StarkParser.ConstantDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.variableDeclarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarators([NotNull] StarkParser.VariableDeclaratorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarator([NotNull] StarkParser.VariableDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.variableStorageCapacity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableStorageCapacity([NotNull] StarkParser.VariableStorageCapacityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableInitializer([NotNull] StarkParser.VariableInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.storageClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStorageClass([NotNull] StarkParser.StorageClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_([NotNull] StarkParser.Type_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.typeQualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeQualifier([NotNull] StarkParser.TypeQualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.nonArrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonArrayType([NotNull] StarkParser.NonArrayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.dynamicType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDynamicType([NotNull] StarkParser.DynamicTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.rawPointerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRawPointerType([NotNull] StarkParser.RawPointerTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.functionPointerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionPointerType([NotNull] StarkParser.FunctionPointerTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.functionPointerSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionPointerSignature([NotNull] StarkParser.FunctionPointerSignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.closureType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClosureType([NotNull] StarkParser.ClosureTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.closureStoragePrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClosureStoragePrefix([NotNull] StarkParser.ClosureStoragePrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.closureSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClosureSignature([NotNull] StarkParser.ClosureSignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.closureCallCapability"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClosureCallCapability([NotNull] StarkParser.ClosureCallCapabilityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.functionPointerParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionPointerParameterList([NotNull] StarkParser.FunctionPointerParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.simpleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleType([NotNull] StarkParser.SimpleTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.integerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerType([NotNull] StarkParser.IntegerTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.builtinType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBuiltinType([NotNull] StarkParser.BuiltinTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.arraySuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArraySuffix([NotNull] StarkParser.ArraySuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.rangeConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRangeConstraint([NotNull] StarkParser.RangeConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.rangeEndpointToken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRangeEndpointToken([NotNull] StarkParser.RangeEndpointTokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.typeArgumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeArgumentList([NotNull] StarkParser.TypeArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] StarkParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] StarkParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.unsafeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnsafeStatement([NotNull] StarkParser.UnsafeStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.assumeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssumeStatement([NotNull] StarkParser.AssumeStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.localConstantDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalConstantDeclaration([NotNull] StarkParser.LocalConstantDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalVariableDeclaration([NotNull] StarkParser.LocalVariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] StarkParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.disjointRuntimeCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDisjointRuntimeCondition([NotNull] StarkParser.DisjointRuntimeConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStatement([NotNull] StarkParser.SwitchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.switchSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchSection([NotNull] StarkParser.SwitchSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchLabel([NotNull] StarkParser.SwitchLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.whenClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhenClause([NotNull] StarkParser.WhenClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] StarkParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] StarkParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.forInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForInitializer([NotNull] StarkParser.ForInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.localForVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalForVariableDeclaration([NotNull] StarkParser.LocalForVariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.forCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForCondition([NotNull] StarkParser.ForConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.forIterator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForIterator([NotNull] StarkParser.ForIteratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.loopBehavior"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoopBehavior([NotNull] StarkParser.LoopBehaviorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.loopContract"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoopContract([NotNull] StarkParser.LoopContractContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.weightSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeightSpecifier([NotNull] StarkParser.WeightSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] StarkParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] StarkParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStatement([NotNull] StarkParser.ContinueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] StarkParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.emptyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyStatement([NotNull] StarkParser.EmptyStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPattern([NotNull] StarkParser.PatternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.aggregatePattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregatePattern([NotNull] StarkParser.AggregatePatternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.genericEnumAggregatePattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericEnumAggregatePattern([NotNull] StarkParser.GenericEnumAggregatePatternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.aggregatePatternSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregatePatternSuffix([NotNull] StarkParser.AggregatePatternSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.enumNamedFieldPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumNamedFieldPattern([NotNull] StarkParser.EnumNamedFieldPatternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.enumNamedFieldPatternPayload"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumNamedFieldPatternPayload([NotNull] StarkParser.EnumNamedFieldPatternPayloadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.namedPatternMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedPatternMember([NotNull] StarkParser.NamedPatternMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] StarkParser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] StarkParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentExpression([NotNull] StarkParser.AssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentOperator([NotNull] StarkParser.AssignmentOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalExpression([NotNull] StarkParser.ConditionalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOrExpression([NotNull] StarkParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalAndExpression([NotNull] StarkParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.bitwiseOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseOrExpression([NotNull] StarkParser.BitwiseOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.bitwiseXorExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseXorExpression([NotNull] StarkParser.BitwiseXorExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.bitwiseAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseAndExpression([NotNull] StarkParser.BitwiseAndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExpression([NotNull] StarkParser.EqualityExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpression([NotNull] StarkParser.RelationalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShiftExpression([NotNull] StarkParser.ShiftExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] StarkParser.AdditiveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpression([NotNull] StarkParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] StarkParser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOperator([NotNull] StarkParser.UnaryOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.conversionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConversionType([NotNull] StarkParser.ConversionTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.conversionNonArrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConversionNonArrayType([NotNull] StarkParser.ConversionNonArrayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.powerExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPowerExpression([NotNull] StarkParser.PowerExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixExpression([NotNull] StarkParser.PostfixExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.postfixPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixPart([NotNull] StarkParser.PostfixPartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpression([NotNull] StarkParser.PrimaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.lambdaExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaExpression([NotNull] StarkParser.LambdaExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.lambdaStoragePrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaStoragePrefix([NotNull] StarkParser.LambdaStoragePrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.captureClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaptureClause([NotNull] StarkParser.CaptureClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.captureBinding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaptureBinding([NotNull] StarkParser.CaptureBindingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.captureMode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaptureMode([NotNull] StarkParser.CaptureModeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.lambdaParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaParameterList([NotNull] StarkParser.LambdaParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.enumConstructorExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumConstructorExpression([NotNull] StarkParser.EnumConstructorExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.objectCreationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectCreationExpression([NotNull] StarkParser.ObjectCreationExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.enumConstructorInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumConstructorInitializer([NotNull] StarkParser.EnumConstructorInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.enumConstructorMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumConstructorMember([NotNull] StarkParser.EnumConstructorMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] StarkParser.ArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] StarkParser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.objectInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectInitializer([NotNull] StarkParser.ObjectInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.memberInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberInitializer([NotNull] StarkParser.MemberInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayInitializer([NotNull] StarkParser.ArrayInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] StarkParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.signedIntegerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignedIntegerLiteral([NotNull] StarkParser.SignedIntegerLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.genericQualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericQualifiedName([NotNull] StarkParser.GenericQualifiedNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.genericEnumCaseReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericEnumCaseReference([NotNull] StarkParser.GenericEnumCaseReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedName([NotNull] StarkParser.QualifiedNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.dottedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDottedName([NotNull] StarkParser.DottedNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StarkParser.enumCaseTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumCaseTarget([NotNull] StarkParser.EnumCaseTargetContext context);
}
} // namespace Stark.Parsing
