[solution]
name = "StarkRepo"
members = [
  "stdlib",
  "vendor",
  "examples/raylib",
  "examples/breakout",
]

[defaults]
build = ["examples/breakout"]
run = "examples/breakout"

[aliases]
stdlib = "stdlib"
vendor = "vendor"
raylib = "examples/raylib"
breakout = "examples/breakout"

[profiles.dev]
opt = 0

[profiles.release]
opt = 3
