[project]
name = "stdlib-text-tests"
version = "0.1.0"
kind = "test"

[test]
root = "TextBuilderTests.stark"
output = "stdlib-text-tests"

[dependencies]
stdlib = { path = "../../stdlib" }

[profiles.dev]
opt = 0

[profiles.release]
opt = 3
