[project]
name = "selfhost-lexing-tests"
version = "0.1.0"
kind = "test"

[test]
root = "LexingTests.stark"
output = "selfhost-lexing-tests"

[dependencies]
stark-compiler = { path = "../../selfhost" }
stdlib = { path = "../../stdlib" }

[profiles.dev]
opt = 0
