[project]
name = "stdlib-filesystem-tests"
version = "0.1.0"
kind = "test"

[test]
root = "FileSystemSymlinkTests.stark"
output = "stdlib-filesystem-tests"

[dependencies]
stdlib = { path = "../../stdlib" }

[profiles.dev]
opt = 0

[profiles.release]
opt = 3
